name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check commit message for 'deploy'
        run: |
          if [[ $(git log -1 --pretty=%B) == *deploy* ]]; then
            echo "Deploy keyword found in commit message."
            exit 0
          else
            echo "Deploy keyword not found in commit message. Skipping deployment."
            exit 78
          fi

      - name: Stop and remove existing container
        run: |
          docker stop suwiki-web || true
          docker rm suwiki-web || true

      - name: Remove existing image
        run: |
          docker rmi suwiki-web || true

      - name: Prune Docker system
        run: |
          docker system prune -a

      - name: Build Docker image
        run: |
          docker build --no-cache -t suwiki-web .

      - name: Run Docker container
        run: |
          docker run -d -p 3000:3000 --name suwiki-web suwiki-web:latest
